# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default='Title'),
        ),
    ]
